#!/usr/bin/env bash

. ./lib

function usage {
    log "Usage: $0 (show|reset|<milisseconds>)"
}

if (($# < 1)); then
    usage
    exit 1
fi;

case "$1" in
    "reset")
        reset
        ;;
    "show")
        show
        ;;
    *)
        latency $1
        ;;
esac

