#!/usr/bin/env bash

. ./lib

function usage {
    log "Usage: $0 (<milisseconds>|show|clear)"
}

if (($# < 1)); then
    usage
    exit 1
fi;

case "$1" in
    "clear")
        reset
        ;;
    "show")
        show
        ;;
    *)
        latency $1
        ;;
esac

