#!/usr/bin/env bash

log() { 
    printf '%s\n' "$@"
}

reset() {
    sudo tc qdisc delete dev lo root 2>/dev/null
    if [[ $? -eq 0 ]]; then
        log "Reseted!"
    else
        log "Nothing to reset!"
    fi
}

show() {
    output=`tc -s qdisc show dev lo`
    if [[ -z $output ]]; then
        echo "Nothing to show!"
    else
        log "$output"
    fi
}

latency() { # $1 : latency
    sudo tc qdisc add dev lo root netem delay $1ms 2>/dev/null
    case "$?" in
        0)
            log "Added $1ms"
            ;;
        1)
            log "Error! Must be a valid number."            
            ;;
        2)  
            sudo tc qdisc change dev lo root netem delay $1ms
            log "Changed to $1ms"
            ;;
        *)  
            log "Error! Unkown error"
            ;;
    esac
}

